name: Pyhton Pipeline

on: [push]

jobs:

  j-checkout-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
            
  j-build:
    runs-on: ubuntu-latest
    needs: [j-checkout-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: .


