name: Pyhton Pipeline

on: [push]

jobs:

  checkout-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
            
  build:
    runs-on: ubuntu-latest
    needs: [checkout-run]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: .


